<!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="generator" content="Hugo 0.31" />

  <title>Como usar o R para escolher um lugar para morar(1) - Web Scraping e Data Cleaning &middot; Paixão por Dados</title>

  
  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pure/1.0.0/pure-min.css">

  <!--[if lte IE 8]>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pure/1.0.0/grids-responsive-old-ie-min.css">
  <![endif]-->
  <!--[if gt IE 8]><!-->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pure/1.0.0/grids-responsive-min.css">
  <!--<![endif]-->

  <!--[if lte IE 8]>
  <link rel="stylesheet" href="/css/side-menu-old-ie.css">
  <![endif]-->
  <!--[if gt IE 8]><!-->
  <link rel="stylesheet" href="/css/side-menu.css">
  <!--<![endif]-->

  <link rel="stylesheet" href="/css/blackburn.css">

  
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

  
  <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet" type="text/css">

  
  

  
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/androidstudio.min.css">
  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
  
  <script>hljs.initHighlightingOnLoad();</script>
  

  <link rel="shortcut icon" href="/img/favicon.ico" type="image/x-icon" />

  
  

</head>


<body>
<div id="layout">

  
<a href="#menu" id="menuLink" class="menu-link">
  
  <span></span>
</a>
<div id="menu">

  

  <div class="pure-menu">
    <ul class="pure-menu-list">
      
      
        <li class="pure-menu-item">
          <a class="pure-menu-link" href="/"><i class='fa fa-home fa-fw'></i>Home</a>
      
        </li>
      
      
        <li class="pure-menu-item">
          <a class="pure-menu-link" href="/post/"><i class='fa fa-list fa-fw'></i>Posts</a>
      
        </li>
      
      
        <li class="pure-menu-item">
          <a class="pure-menu-link" href="/about/"><i class='fa fa-user fa-fw'></i>Sobre</a>
      
        </li>
      
      
        <li class="pure-menu-item">
          <a class="pure-menu-link" href="/contact/"><i class='fa fa-phone fa-fw'></i>Contato</a>
      
        </li>
      
    </ul>
  </div>

  <div class="pure-menu social">
  <ul class="pure-menu-list">

    

    

    

    

    
    <li class="pure-menu-item">
      <a class="pure-menu-link" href="https://facebook.com/sillast" target="_blank"><i class="fa fa-facebook-square fa-fw"></i>Facebook</a>
    </li>
    

    

    

    

    

    

    

    

    

    

    

    

    

    

    
    <li class="pure-menu-item">
      <a class="pure-menu-link" href="https://linkedin.com/in/sillasgonzaga" target="_blank"><i class="fa fa-linkedin-square fa-fw"></i>LinkedIn</a>
    </li>
    

    

    

    

    

    

    
    <li class="pure-menu-item">
      <a class="pure-menu-link" href="https://github.com/sillasgonzaga" target="_blank"><i class="fa fa-github-square fa-fw"></i>GitHub</a>
    </li>
    

    

    

    

    

    

    

    

    

    

    

    

    

  </ul>
</div>


  <div>
  <div class="small-print">
    <small>&copy; 2016. All rights reserved.</small>
  </div>
  <div class="small-print">
    <small>Built with&nbsp;<a href="https://gohugo.io/" target="_blank">Hugo</a></small>
    <small>Theme&nbsp;<a href="https://github.com/yoshiharuyamashita/blackburn" target="_blank">Blackburn</a></small>
  </div>
</div>

</div>


  <div id="main">


<div class="header">
  <h1>Como usar o R para escolher um lugar para morar(1) - Web Scraping e Data Cleaning</h1>
  <h2></h2>
</div>
<div class="content">

  <div class="post-meta">

  <div>
    <i class="fa fa-calendar fa-fw"></i>
    <time>17 Nov 2016</time>
  </div>

  

  

  
  
  
  <div>
    <i class="fa fa-tags fa-fw"></i>
    
      <a class="post-taxonomy-tag" href="/tags/web-scraping">web scraping</a>&nbsp;&#47;
    
      <a class="post-taxonomy-tag" href="/tags/olx">olx</a>
    
  </div>
  
  

</div>

  <div id="introducao" class="section level1">
<h1>Introdução</h1>
<p>Imagine-se na seguinte situação: você foi convidado a se mudar para a cidade do Rio de Janeiro a trabalho e precisa procurar um lugar para morar. Pessoas normais resolveriam esse problema pesquisando preços de apartamentos ou quartos para alugar em sites como OLX ou AirBNB. Mas como alguém fascinado em programação e análise resolveria?</p>
<p>Nesta série de posts, mostro como o R pode ser usado tomar a decisão sobre escolher um apartamento ou quarto para alugar. No OLX, a formatação HTML das páginas de apartamentos são diferentes das de quartos. Neste post, eu mostro como fazer o web scraping, por meio do pacote <code>rvest</code>, apenas de apartamentos, mas o mesmo procedimento (com pequenas modificações) pode ser feito também para quartos.</p>
<p>As bibliotecas usadas serão:</p>
<pre class="r"><code>library(magrittr) # não vivo sem esse pacote
library(rvest) # principal pacote para web-scraping
library(readr) # usado para extrair numeros de texto
library(stringr) # usado para o data cleaning
library(curl) # usado como suporte para o rvest
library(tidyr) # data cleaning
library(dplyr) # data cleaning
source(&quot;/home/sillas/R/Projetos/olx/funcoes.R&quot;) # algumas funcoes que criei para auxiliar o data cleaning</code></pre>
</div>
<div id="web-scraping" class="section level1">
<h1>Web scraping</h1>
<p>A primeira etapa é obter os dados. Até a data de hoje (12 de Novembro de 2016), o <a href="http://rj.olx.com.br/rio-de-janeiro-e-regiao/imoveis/aluguel/apartamentos">OLX</a> listava um pouco mais de 12000 apartamentos para alugar, com 245 páginas e 50 apartamentos em cada página.</p>
<pre class="r"><code>url_apt &lt;- &quot;http://rj.olx.com.br/rio-de-janeiro-e-regiao/imoveis/aluguel/apartamentos&quot;
number_pages &lt;- 245 #hard coded
# Criar vetor com todos os urls para as páginas do olx
lista_urls &lt;- paste0(url_apt, &quot;?o=&quot;, 1:number_pages)</code></pre>
<p>A seguir, eu uso uma função para extrair as informações importantes de cada anúncio, que são: o link para o anúncio, o título, o preço, o bairro e mais algumas informações adicionais, como número de vagas de garagem e o valor da taxa de condomínio. Explicar o passo-a-passo do web scraping e explicar como o código fonte das páginas do OLX funciona está fora do escopo deste post, mas acredito que basta ler o código da função extrairAnuncios() para entender o que o script faz. Caso o leitor deseje saber mais sobre web scraping, o post 3 da série traz um tutorial de web scraping bem detalhado.</p>
<pre class="r"><code>extrairAnuncios &lt;- function(url_pagina, info_adicional) {
  ### INPUTS:
  # url_pagina: url de uma pagina do olx com uma lista de links de anúncios.
  # info_adicional: variavel booleana. se verdadeiro, faz o scraping de dados adicionais do anuncio
  # ... deve ser usado apenas para apartamentos, pois a sintaxe do html para quartos é diferente
  mycurl &lt;- curl(url_pagina, handle = curl::new_handle(&quot;useragent&quot; = &quot;Mozilla/5.0&quot;))
  mycurl &lt;- read_html(mycurl)

  x &lt;- mycurl %&gt;% html_nodes(&quot;.OLXad-list-link&quot;)
  
  # extrair link do anuncio
  col_links &lt;- mycurl %&gt;% html_nodes(&quot;.OLXad-list-link&quot;) %&gt;% html_attr(&quot;href&quot;)
  # extrair titulo do anuncio
  col_titles &lt;- mycurl %&gt;% html_nodes(&quot;.OLXad-list-link&quot;) %&gt;% html_attr(&quot;title&quot;)
  # extrair preço
  precos &lt;- lapply(x, . %&gt;% html_nodes(&quot;.col-3&quot;))
  precos %&lt;&gt;% lapply(html_text)
  precos %&lt;&gt;% unlist()
  precos %&lt;&gt;% limparString()
  precos %&lt;&gt;% as.numeric()
  col_precos &lt;- precos
  # extrair bairros
  bairros &lt;- mycurl %&gt;% html_nodes(&quot;.OLXad-list-line-2&quot;) %&gt;% html_text()
  bairros %&lt;&gt;% str_replace_all(&quot;[\t]&quot;, &quot;&quot;)
  bairros %&lt;&gt;% str_replace_all(&quot;[\n]&quot;, &quot;&quot;)
  bairros %&lt;&gt;% str_replace_all(&quot;Apartamentos&quot;, &quot;&quot;)
  bairros %&lt;&gt;% str_replace_all(&quot;Aluguel de quartos&quot;, &quot;&quot;)
  bairros %&lt;&gt;% str_replace_all(&quot;Anúncio Profissional&quot;, &quot;&quot;)
  bairros %&lt;&gt;% str_replace(&quot;-&quot;, &quot;&quot;)
  bairros %&lt;&gt;% str_trim()
  col_bairros &lt;- bairros
  # extrair informações adicionais de apartamento
  
  if (info_adicional) {
    adicional &lt;- mycurl %&gt;% html_nodes(&quot;.mt5px&quot;) %&gt;% html_text()
    adicional %&lt;&gt;% str_replace_all(&quot;[\t]&quot;, &quot;&quot;)
    adicional %&lt;&gt;% str_replace_all(&quot;[\n]&quot;, &quot;&quot;)
    col_adicionais &lt;- adicional
    
  }
    return(data.frame(link = col_links,
                    titulo = col_titles,
                    preco = col_precos,
                    bairro = col_bairros,
                    adicional = col_adicionais,
                    stringsAsFactors = FALSE))
}</code></pre>
<p>Agora já podemos aplicar a função <code>extrairAnuncios()</code> no vetor da lista de urls para baixar os dados. Para fins de demonstração, vou executar o procedimento apenas para a primeira página.</p>
<pre class="r"><code>url_teste &lt;- lista_urls[1]
system.time(df &lt;- extrairAnuncios(url_teste, info_adicional = TRUE))</code></pre>
<pre><code>##   usuário   sistema decorrido 
##     1.084     0.028    11.953</code></pre>
<pre class="r"><code># Vamos dar uma olhada nos dados
head(df) %&gt;% knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">link</th>
<th align="left">titulo</th>
<th align="right">preco</th>
<th align="left">bairro</th>
<th align="left">adicional</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><a href="http://rj.olx.com.br/rio-de-janeiro-e-regiao/imoveis/apartamento-de-2-quartos-no-rio-centro-417491615" class="uri">http://rj.olx.com.br/rio-de-janeiro-e-regiao/imoveis/apartamento-de-2-quartos-no-rio-centro-417491615</a></td>
<td align="left">Apartamento de 2 quartos no Rio Centro</td>
<td align="right">1500</td>
<td align="left">Rio de Janeiro, Camorim</td>
<td align="left">2 quartos | Condomínio: R$ 550 | 1 vaga</td>
</tr>
<tr class="even">
<td align="left"><a href="http://rj.olx.com.br/rio-de-janeiro-e-regiao/imoveis/apartamento-no-meier-vilela-tavares-417491090" class="uri">http://rj.olx.com.br/rio-de-janeiro-e-regiao/imoveis/apartamento-no-meier-vilela-tavares-417491090</a></td>
<td align="left">Apartamento no Méier- Vilela Tavares</td>
<td align="right">1600</td>
<td align="left">Rio de Janeiro, Méier</td>
<td align="left">2 quartos | 60 m² | Condomínio: R$ 650</td>
</tr>
<tr class="odd">
<td align="left"><a href="http://rj.olx.com.br/rio-de-janeiro-e-regiao/imoveis/vip-aluga-lindo-apartamento-2-quartos-com-armarios-417489866" class="uri">http://rj.olx.com.br/rio-de-janeiro-e-regiao/imoveis/vip-aluga-lindo-apartamento-2-quartos-com-armarios-417489866</a></td>
<td align="left">(Vip Aluga) Lindo apartamento 2 quartos com armários</td>
<td align="right">900</td>
<td align="left">Rio de Janeiro, Campo Grande</td>
<td align="left">2 quartos | 48 m² | Condomínio: R$ 310 | 1 vaga</td>
</tr>
<tr class="even">
<td align="left"><a href="http://rj.olx.com.br/rio-de-janeiro-e-regiao/imoveis/tijuquinha-kitinete-itanhanga-417487116" class="uri">http://rj.olx.com.br/rio-de-janeiro-e-regiao/imoveis/tijuquinha-kitinete-itanhanga-417487116</a></td>
<td align="left">Tijuquinha kitinete Itanhangá</td>
<td align="right">750</td>
<td align="left">Rio de Janeiro, Itanhangá</td>
<td align="left">1 quarto</td>
</tr>
<tr class="odd">
<td align="left"><a href="http://rj.olx.com.br/rio-de-janeiro-e-regiao/imoveis/apartamento-de-3-quartos-com-dep-no-recreio-417487754" class="uri">http://rj.olx.com.br/rio-de-janeiro-e-regiao/imoveis/apartamento-de-3-quartos-com-dep-no-recreio-417487754</a></td>
<td align="left">Apartamento de 3 quartos com dep. no Recreio</td>
<td align="right">2500</td>
<td align="left">Rio de Janeiro, Recreio Dos Bandeirantes</td>
<td align="left">3 quartos | 107 m² | Condomínio: R$ 880 | 1 vaga</td>
</tr>
<tr class="even">
<td align="left"><a href="http://rj.olx.com.br/rio-de-janeiro-e-regiao/imoveis/apartamento-concetto-recreio-2-quartos-mobiliado-opcional-consulte-primeira-locacao-417487425" class="uri">http://rj.olx.com.br/rio-de-janeiro-e-regiao/imoveis/apartamento-concetto-recreio-2-quartos-mobiliado-opcional-consulte-primeira-locacao-417487425</a></td>
<td align="left">Apartamento Concetto Recreio, 2 Quartos, Mobiliado (Opcional, Consulte)- Primeira Locação</td>
<td align="right">1799</td>
<td align="left">Rio de Janeiro, Recreio Dos Bandeirantes</td>
<td align="left">2 quartos | 82 m² | Condomínio: R$ 492 | 1 vaga</td>
</tr>
</tbody>
</table>
</div>
<div id="data-cleaning" class="section level1">
<h1>Data Cleaning</h1>
<p>Pode-se ver que o web scraping (ao menos para esses 5 exemplos) foi bem feito pois os os dados foram extraídos adequadamente. Contudo, é evidente a necessidade de se limpar os dados para poder os analisar. A coluna de informações adicionais, por exemplo, informa dados de até quatro variáveis: quantidade de quartos, quantidade de vagas de garagem, área e o preço da taxa de condomínio. Para deixar o processo de limpeza ainda mais difícil, nem todos os anúncios fornecem dados dessas quatro variáveis.</p>
<p>Antes de partir para esse problema, vamos separa a coluna de bairro em duas: uma de cidade e outra de bairro. Removi os imóveis que não são do Rio de Janeiro ou de Niterói para fins de simplicidade.</p>
<pre class="r"><code># remover os que nao sao do RJ ou de niteroi
df %&lt;&gt;% filter(str_detect(bairro, &quot;Niterói&quot;) | str_detect(bairro, &quot;Rio de Janeiro&quot;))
df %&lt;&gt;% separate(bairro, c(&quot;cidade&quot;, &quot;bairro&quot;), sep = &quot;,&quot;)
head(df) %&gt;% knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">link</th>
<th align="left">titulo</th>
<th align="right">preco</th>
<th align="left">cidade</th>
<th align="left">bairro</th>
<th align="left">adicional</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><a href="http://rj.olx.com.br/rio-de-janeiro-e-regiao/imoveis/apartamento-de-2-quartos-no-rio-centro-417491615" class="uri">http://rj.olx.com.br/rio-de-janeiro-e-regiao/imoveis/apartamento-de-2-quartos-no-rio-centro-417491615</a></td>
<td align="left">Apartamento de 2 quartos no Rio Centro</td>
<td align="right">1500</td>
<td align="left">Rio de Janeiro</td>
<td align="left">Camorim</td>
<td align="left">2 quartos | Condomínio: R$ 550 | 1 vaga</td>
</tr>
<tr class="even">
<td align="left"><a href="http://rj.olx.com.br/rio-de-janeiro-e-regiao/imoveis/apartamento-no-meier-vilela-tavares-417491090" class="uri">http://rj.olx.com.br/rio-de-janeiro-e-regiao/imoveis/apartamento-no-meier-vilela-tavares-417491090</a></td>
<td align="left">Apartamento no Méier- Vilela Tavares</td>
<td align="right">1600</td>
<td align="left">Rio de Janeiro</td>
<td align="left">Méier</td>
<td align="left">2 quartos | 60 m² | Condomínio: R$ 650</td>
</tr>
<tr class="odd">
<td align="left"><a href="http://rj.olx.com.br/rio-de-janeiro-e-regiao/imoveis/vip-aluga-lindo-apartamento-2-quartos-com-armarios-417489866" class="uri">http://rj.olx.com.br/rio-de-janeiro-e-regiao/imoveis/vip-aluga-lindo-apartamento-2-quartos-com-armarios-417489866</a></td>
<td align="left">(Vip Aluga) Lindo apartamento 2 quartos com armários</td>
<td align="right">900</td>
<td align="left">Rio de Janeiro</td>
<td align="left">Campo Grande</td>
<td align="left">2 quartos | 48 m² | Condomínio: R$ 310 | 1 vaga</td>
</tr>
<tr class="even">
<td align="left"><a href="http://rj.olx.com.br/rio-de-janeiro-e-regiao/imoveis/tijuquinha-kitinete-itanhanga-417487116" class="uri">http://rj.olx.com.br/rio-de-janeiro-e-regiao/imoveis/tijuquinha-kitinete-itanhanga-417487116</a></td>
<td align="left">Tijuquinha kitinete Itanhangá</td>
<td align="right">750</td>
<td align="left">Rio de Janeiro</td>
<td align="left">Itanhangá</td>
<td align="left">1 quarto</td>
</tr>
<tr class="odd">
<td align="left"><a href="http://rj.olx.com.br/rio-de-janeiro-e-regiao/imoveis/apartamento-de-3-quartos-com-dep-no-recreio-417487754" class="uri">http://rj.olx.com.br/rio-de-janeiro-e-regiao/imoveis/apartamento-de-3-quartos-com-dep-no-recreio-417487754</a></td>
<td align="left">Apartamento de 3 quartos com dep. no Recreio</td>
<td align="right">2500</td>
<td align="left">Rio de Janeiro</td>
<td align="left">Recreio Dos Bandeirantes</td>
<td align="left">3 quartos | 107 m² | Condomínio: R$ 880 | 1 vaga</td>
</tr>
<tr class="even">
<td align="left"><a href="http://rj.olx.com.br/rio-de-janeiro-e-regiao/imoveis/apartamento-concetto-recreio-2-quartos-mobiliado-opcional-consulte-primeira-locacao-417487425" class="uri">http://rj.olx.com.br/rio-de-janeiro-e-regiao/imoveis/apartamento-concetto-recreio-2-quartos-mobiliado-opcional-consulte-primeira-locacao-417487425</a></td>
<td align="left">Apartamento Concetto Recreio, 2 Quartos, Mobiliado (Opcional, Consulte)- Primeira Locação</td>
<td align="right">1799</td>
<td align="left">Rio de Janeiro</td>
<td align="left">Recreio Dos Bandeirantes</td>
<td align="left">2 quartos | 82 m² | Condomínio: R$ 492 | 1 vaga</td>
</tr>
</tbody>
</table>
<p>Agora podemos partir para a limpeza da coluna de adicionais. Primeiramente, vamos ver quantos anúncios possuem as quatro variáveis adicionais:</p>
<pre class="r"><code># substituir quartos por quarto
df$adicional %&lt;&gt;% str_replace_all(&quot;quartos&quot;, &quot;quarto&quot;)
df %&lt;&gt;% mutate(
  tem_quarto = str_detect(adicional, &quot;quarto&quot;),
  tem_area = str_detect(adicional, &quot;m²&quot;),
  tem_taxa = str_detect(adicional, &quot;Condomínio&quot;),
  tem_garagem = str_detect(adicional, &quot;vaga&quot;)
)

x &lt;- round(apply(df[, 7:10], 2, mean), 3) * 100
print(x)</code></pre>
<pre><code>##  tem_quarto    tem_area    tem_taxa tem_garagem 
##       100.0        87.5        79.2        64.6</code></pre>
<p>Assim, 100% dos apartamentos (dessa amostra de 50 apartamentos) têm informação sobre a quantidade de quartos, 87.5% sobre área, 79.2% informam a taxa de condomínio e 64.6% têm vaga de garagem.</p>
<p>É necessário usar o pacote <code>stringr</code> para observar a posição dos termos que identificam a variável:<br />
* O substring “quarto” indica a presença de informação sobre quantidade de quartos;<br />
* O substring “Condomínio: R$” indica a presença de informação sobre taxa do condomínio;<br />
* O substring “m²” indica a presença de informação sobre área;<br />
* O substring “vaga” indica a presença de informação sobre vagas de garagem.</p>
<p>O desafio aqui é criar colunas adicionais para cada uma dessas categorias de informação adicional. A seguir, eu comento linha a linha o procedimento necessário para realizar essa tarefa, que é basicamente o mesmo para as variáveis.</p>
<pre class="r"><code># COLUNA DE QUANTIDADE DE QUARTOS
# Quarto: pegar posicao inicial e final do string quarto
# Localizar trecho dentro do string referente a quartos
matriz_posicao &lt;- str_locate(df$adicional, &quot;quarto&quot;)
# Voltar 2 posições no string para pegar o número (ex: 2 quarto)
matriz_posicao[,1] &lt;- matriz_posicao[,1] - 2
# extrair string com posições iniciais e finais
vetor_quartos &lt;- str_sub(df$adicional, matriz_posicao[,1], matriz_posicao[,2])
# extrair apenas número (primeiro caractere do string) e converter para numeric
vetor_quartos &lt;- str_sub(vetor_quartos, 1, 1)
vetor_quartos %&lt;&gt;% as.numeric()
# adicionar ao data frame
df$qtd_quarto &lt;- vetor_quartos


# Condominio
# retirar cifrao pra ficar mais facil
df$adicional %&lt;&gt;% str_replace_all(&quot;\\$&quot;, &quot;S&quot;)
matriz_posicao &lt;- str_locate(df$adicional, &quot;Condomínio: RS &quot;)
# mover cinco posicoes para pegar algarismos após o RS
vetor_taxa &lt;- str_sub(df$adicional, matriz_posicao[, 2], matriz_posicao[, 2] + 4)
# extrair apenas numeros
vetor_taxa %&lt;&gt;% parse_number()
# vendo se funcionou
data.frame(df$adicional, vetor_taxa) %&gt;% head(20)</code></pre>
<pre><code>##                                        df.adicional vetor_taxa
## 1            2 quarto | Condomínio: RS 550 | 1 vaga        550
## 2             2 quarto | 60 m² | Condomínio: RS 650        650
## 3    2 quarto | 48 m² | Condomínio: RS 310 | 1 vaga        310
## 4                                          1 quarto         NA
## 5   3 quarto | 107 m² | Condomínio: RS 880 | 1 vaga        880
## 6    2 quarto | 82 m² | Condomínio: RS 492 | 1 vaga        492
## 7    2 quarto | 51 m² | Condomínio: RS 504 | 1 vaga        504
## 8                                  1 quarto | 58 m²         NA
## 9   2 quarto | 140 m² | Condomínio: RS 135 | 1 vaga        135
## 10   2 quarto | 50 m² | Condomínio: RS 315 | 1 vaga        315
## 11   2 quarto | 72 m² | Condomínio: RS 620 | 1 vaga        620
## 12           2 quarto | 60 m² | Condomínio: RS 1200       1200
## 13   2 quarto | 49 m² | Condomínio: RS 290 | 1 vaga        290
## 14                                         1 quarto         NA
## 15   2 quarto | 76 m² | Condomínio: RS 980 | 1 vaga        980
## 16  3 quarto | 72 m² | Condomínio: RS 490 | 2 vagas        490
## 17  2 quarto | 80 m² | Condomínio: RS 1100 | 1 vaga       1100
## 18                        1 quarto | 45 m² | 1 vaga         NA
## 19                                         2 quarto         NA
## 20                                3 quarto | 1 vaga         NA</code></pre>
<pre class="r"><code># Funcionou! Incorporar vetor ao data frame
df$taxa_condominio &lt;- vetor_taxa


# Área
matriz_posicao &lt;- str_locate(df$adicional, &quot; m²&quot;)
# voltar quatro posições
vetor_area &lt;- str_sub(df$adicional, matriz_posicao[,1] - 4, matriz_posicao[, 1])
# converter para numerico
vetor_area %&lt;&gt;% parse_number()
# vendo se funcionou
data.frame(df$adicional, vetor_area) %&gt;% head(20)</code></pre>
<pre><code>##                                        df.adicional vetor_area
## 1            2 quarto | Condomínio: RS 550 | 1 vaga         NA
## 2             2 quarto | 60 m² | Condomínio: RS 650         60
## 3    2 quarto | 48 m² | Condomínio: RS 310 | 1 vaga         48
## 4                                          1 quarto         NA
## 5   3 quarto | 107 m² | Condomínio: RS 880 | 1 vaga        107
## 6    2 quarto | 82 m² | Condomínio: RS 492 | 1 vaga         82
## 7    2 quarto | 51 m² | Condomínio: RS 504 | 1 vaga         51
## 8                                  1 quarto | 58 m²         58
## 9   2 quarto | 140 m² | Condomínio: RS 135 | 1 vaga        140
## 10   2 quarto | 50 m² | Condomínio: RS 315 | 1 vaga         50
## 11   2 quarto | 72 m² | Condomínio: RS 620 | 1 vaga         72
## 12           2 quarto | 60 m² | Condomínio: RS 1200         60
## 13   2 quarto | 49 m² | Condomínio: RS 290 | 1 vaga         49
## 14                                         1 quarto         NA
## 15   2 quarto | 76 m² | Condomínio: RS 980 | 1 vaga         76
## 16  3 quarto | 72 m² | Condomínio: RS 490 | 2 vagas         72
## 17  2 quarto | 80 m² | Condomínio: RS 1100 | 1 vaga         80
## 18                        1 quarto | 45 m² | 1 vaga         45
## 19                                         2 quarto         NA
## 20                                3 quarto | 1 vaga         NA</code></pre>
<pre class="r"><code># Funcionou! Incorporar ao data frame
df$area_condominio &lt;- vetor_area


# Garagem
matriz_posicao &lt;- str_locate(df$adicional, &quot; vaga&quot;)
# voltar quatro posições
vetor_garagem &lt;- str_sub(df$adicional, matriz_posicao[,1] - 2, matriz_posicao[, 1])
# converter para numerico
vetor_garagem %&lt;&gt;% readr::parse_number()
# vendo se funcionou
data.frame(df$adicional, vetor_garagem) %&gt;% head(20)</code></pre>
<pre><code>##                                        df.adicional vetor_garagem
## 1            2 quarto | Condomínio: RS 550 | 1 vaga             1
## 2             2 quarto | 60 m² | Condomínio: RS 650            NA
## 3    2 quarto | 48 m² | Condomínio: RS 310 | 1 vaga             1
## 4                                          1 quarto            NA
## 5   3 quarto | 107 m² | Condomínio: RS 880 | 1 vaga             1
## 6    2 quarto | 82 m² | Condomínio: RS 492 | 1 vaga             1
## 7    2 quarto | 51 m² | Condomínio: RS 504 | 1 vaga             1
## 8                                  1 quarto | 58 m²            NA
## 9   2 quarto | 140 m² | Condomínio: RS 135 | 1 vaga             1
## 10   2 quarto | 50 m² | Condomínio: RS 315 | 1 vaga             1
## 11   2 quarto | 72 m² | Condomínio: RS 620 | 1 vaga             1
## 12           2 quarto | 60 m² | Condomínio: RS 1200            NA
## 13   2 quarto | 49 m² | Condomínio: RS 290 | 1 vaga             1
## 14                                         1 quarto            NA
## 15   2 quarto | 76 m² | Condomínio: RS 980 | 1 vaga             1
## 16  3 quarto | 72 m² | Condomínio: RS 490 | 2 vagas             2
## 17  2 quarto | 80 m² | Condomínio: RS 1100 | 1 vaga             1
## 18                        1 quarto | 45 m² | 1 vaga             1
## 19                                         2 quarto            NA
## 20                                3 quarto | 1 vaga             1</code></pre>
<pre class="r"><code># Funcionou! Incorporar ao data frame
df$garagem &lt;- vetor_garagem

# Remover objetos desnecessários
rm(matriz_posicao, vetor_adicional, vetor_area, vetor_garagem, vetor_quartos, vetor_taxa)</code></pre>
<p>Vamos ver como ficou o data frame final</p>
<pre class="r"><code>head(df) %&gt;% knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">link</th>
<th align="left">titulo</th>
<th align="right">preco</th>
<th align="left">cidade</th>
<th align="left">bairro</th>
<th align="left">adicional</th>
<th align="left">tem_quarto</th>
<th align="left">tem_area</th>
<th align="left">tem_taxa</th>
<th align="left">tem_garagem</th>
<th align="right">qtd_quarto</th>
<th align="right">taxa_condominio</th>
<th align="right">area_condominio</th>
<th align="right">garagem</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><a href="http://rj.olx.com.br/rio-de-janeiro-e-regiao/imoveis/apartamento-de-2-quartos-no-rio-centro-417491615" class="uri">http://rj.olx.com.br/rio-de-janeiro-e-regiao/imoveis/apartamento-de-2-quartos-no-rio-centro-417491615</a></td>
<td align="left">Apartamento de 2 quartos no Rio Centro</td>
<td align="right">1500</td>
<td align="left">Rio de Janeiro</td>
<td align="left">Camorim</td>
<td align="left">2 quarto | Condomínio: RS 550 | 1 vaga</td>
<td align="left">TRUE</td>
<td align="left">FALSE</td>
<td align="left">TRUE</td>
<td align="left">TRUE</td>
<td align="right">2</td>
<td align="right">550</td>
<td align="right">NA</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="left"><a href="http://rj.olx.com.br/rio-de-janeiro-e-regiao/imoveis/apartamento-no-meier-vilela-tavares-417491090" class="uri">http://rj.olx.com.br/rio-de-janeiro-e-regiao/imoveis/apartamento-no-meier-vilela-tavares-417491090</a></td>
<td align="left">Apartamento no Méier- Vilela Tavares</td>
<td align="right">1600</td>
<td align="left">Rio de Janeiro</td>
<td align="left">Méier</td>
<td align="left">2 quarto | 60 m² | Condomínio: RS 650</td>
<td align="left">TRUE</td>
<td align="left">TRUE</td>
<td align="left">TRUE</td>
<td align="left">FALSE</td>
<td align="right">2</td>
<td align="right">650</td>
<td align="right">60</td>
<td align="right">NA</td>
</tr>
<tr class="odd">
<td align="left"><a href="http://rj.olx.com.br/rio-de-janeiro-e-regiao/imoveis/vip-aluga-lindo-apartamento-2-quartos-com-armarios-417489866" class="uri">http://rj.olx.com.br/rio-de-janeiro-e-regiao/imoveis/vip-aluga-lindo-apartamento-2-quartos-com-armarios-417489866</a></td>
<td align="left">(Vip Aluga) Lindo apartamento 2 quartos com armários</td>
<td align="right">900</td>
<td align="left">Rio de Janeiro</td>
<td align="left">Campo Grande</td>
<td align="left">2 quarto | 48 m² | Condomínio: RS 310 | 1 vaga</td>
<td align="left">TRUE</td>
<td align="left">TRUE</td>
<td align="left">TRUE</td>
<td align="left">TRUE</td>
<td align="right">2</td>
<td align="right">310</td>
<td align="right">48</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="left"><a href="http://rj.olx.com.br/rio-de-janeiro-e-regiao/imoveis/tijuquinha-kitinete-itanhanga-417487116" class="uri">http://rj.olx.com.br/rio-de-janeiro-e-regiao/imoveis/tijuquinha-kitinete-itanhanga-417487116</a></td>
<td align="left">Tijuquinha kitinete Itanhangá</td>
<td align="right">750</td>
<td align="left">Rio de Janeiro</td>
<td align="left">Itanhangá</td>
<td align="left">1 quarto</td>
<td align="left">TRUE</td>
<td align="left">FALSE</td>
<td align="left">FALSE</td>
<td align="left">FALSE</td>
<td align="right">1</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
<tr class="odd">
<td align="left"><a href="http://rj.olx.com.br/rio-de-janeiro-e-regiao/imoveis/apartamento-de-3-quartos-com-dep-no-recreio-417487754" class="uri">http://rj.olx.com.br/rio-de-janeiro-e-regiao/imoveis/apartamento-de-3-quartos-com-dep-no-recreio-417487754</a></td>
<td align="left">Apartamento de 3 quartos com dep. no Recreio</td>
<td align="right">2500</td>
<td align="left">Rio de Janeiro</td>
<td align="left">Recreio Dos Bandeirantes</td>
<td align="left">3 quarto | 107 m² | Condomínio: RS 880 | 1 vaga</td>
<td align="left">TRUE</td>
<td align="left">TRUE</td>
<td align="left">TRUE</td>
<td align="left">TRUE</td>
<td align="right">3</td>
<td align="right">880</td>
<td align="right">107</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="left"><a href="http://rj.olx.com.br/rio-de-janeiro-e-regiao/imoveis/apartamento-concetto-recreio-2-quartos-mobiliado-opcional-consulte-primeira-locacao-417487425" class="uri">http://rj.olx.com.br/rio-de-janeiro-e-regiao/imoveis/apartamento-concetto-recreio-2-quartos-mobiliado-opcional-consulte-primeira-locacao-417487425</a></td>
<td align="left">Apartamento Concetto Recreio, 2 Quartos, Mobiliado (Opcional, Consulte)- Primeira Locação</td>
<td align="right">1799</td>
<td align="left">Rio de Janeiro</td>
<td align="left">Recreio Dos Bandeirantes</td>
<td align="left">2 quarto | 82 m² | Condomínio: RS 492 | 1 vaga</td>
<td align="left">TRUE</td>
<td align="left">TRUE</td>
<td align="left">TRUE</td>
<td align="left">TRUE</td>
<td align="right">2</td>
<td align="right">492</td>
<td align="right">82</td>
<td align="right">1</td>
</tr>
</tbody>
</table>
</div>
<div id="conclusao" class="section level1">
<h1>Conclusão</h1>
<p>No próximo post, analisaremos os dados obtidos aqui.</p>
</div>


  
<div class="prev-next-post pure-g">
  <div class="pure-u-1-24" style="text-align: left;">
    
    <a href="/post/mafs01/"><i class="fa fa-chevron-left"></i></a>
    
  </div>
  <div class="pure-u-10-24">
    
    <nav class="prev">
      <a href="/post/mafs01/">Meu primeiro pacote R: aplicação para série temporal do varejo</a>
    </nav>
    
  </div>
  <div class="pure-u-2-24">
    &nbsp;
  </div>
  <div class="pure-u-10-24">
    
    <nav class="next">
      <a href="/post/olx03/">Como usar o R para escolher um lugar para morar (3) - Converter CEP em coordenadas geográficas</a>
    </nav>
    
  </div>
  <div class="pure-u-1-24" style="text-align: right;">
    
    <a href="/post/olx03/"><i class="fa fa-chevron-right"></i></a>
    
  </div>
</div>



  
<div id="disqus_thread"></div>
<script type="text/javascript">

(function() {
    
    
    if (window.location.hostname == "localhost")
        return;

    var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
    var disqus_shortname = 'sillastg';
    dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>


</div>

</div>
</div>
<script src="/js/ui.js"></script>


<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-110050805-1', 'auto');
  ga('send', 'pageview');

</script>





</body>
</html>

